/** /waves — the Elliott Wave dashboard, fed by trading-lab's engine output.
 *
 * Data is a static feed (public/waves/btc.json) regenerated by the engine's
 * pipeline; the page draws it and never recomputes it. Forecast labels are
 * earned through walk-forward testing — until a zone class clears that bar,
 * zones render as structure, and the ledger keeps score in public.
 */
import { useEffect, useState } from "react";
import { FullHistoryChart, RecentChart } from "./charts.tsx";
import type { LedgerRow, Reading, WaveFeed } from "./types.ts";

function fmtMoney(v: number): string {
  return `$${Math.round(v).toLocaleString("en-US")}`;
}

function readingTitle(r: Reading): string {
  const p = r.pattern.replace(/_/g, " ");
  return `${r.degree} ${p}${r.running ? `, wave ${r.running} running` : ""}`;
}

const OUTCOME_STYLE: Record<LedgerRow["outcome"], { dot: string; label: string }> = {
  hit: { dot: "#16c784", label: "Hit" },
  miss: { dot: "#7a8291", label: "Miss" },
  invalidated: { dot: "#ea3943", label: "Invalidated" },
};

export function WavesPage() {
  const [feed, setFeed] = useState<WaveFeed | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;
    fetch("/waves/btc.json")
      .then((r) => {
        if (!r.ok) throw new Error(`feed ${r.status}`);
        return r.json();
      })
      .then((d: WaveFeed) => {
        if (!cancelled) setFeed(d);
      })
      .catch((e: unknown) => {
        if (!cancelled) setError(e instanceof Error ? e.message : String(e));
      });
    return () => {
      cancelled = true;
    };
  }, []);

  if (error) {
    return (
      <div className="flex h-screen items-center justify-center bg-background text-muted-foreground">
        Wave feed unavailable ({error}) — regenerate it with tools/build_wave_feed.py.
      </div>
    );
  }
  if (!feed) {
    return (
      <div className="flex h-screen items-center justify-center bg-background text-muted-foreground">
        Loading wave count…
      </div>
    );
  }

  const leading = feed.readings[0];
  const alt = feed.readings.find((r) => r !== leading && r.degree === leading?.degree);
  const t = feed.ledger_totals;

  return (
    // global.css locks body scrolling for the terminal, so this page scrolls itself
    <div className="h-screen overflow-y-auto bg-background text-foreground text-[13px]">
      {/* top bar */}
      <div className="flex h-14 items-center gap-3.5 border-b border-border bg-card px-5">
        <div className="flex items-center gap-2 border-r border-border pr-3.5">
          <svg width="24" height="24" viewBox="0 0 28 28">
            <rect width="28" height="28" rx="7" fill="#14b8a6" />
            <path d="M4 18 L9 10 L13 15 L18 7 L24 13" fill="none" stroke="#04120f"
              strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round" />
          </svg>
          <span className="text-[15px] font-extrabold tracking-tight">Waves</span>
        </div>
        <span className="flex h-8 items-center gap-2 rounded-md border border-border bg-secondary px-3 text-[13px] font-semibold">
          <span className="flex h-4 w-4 items-center justify-center rounded-full bg-[#f7931a] text-[9px] font-bold text-white">₿</span>
          {feed.pair}
        </span>
        <div className="ml-auto flex items-baseline gap-2">
          <span className="font-mono text-[15px] font-semibold">{fmtMoney(feed.price_now)}</span>
          <span className="text-xs text-muted-foreground">as of {feed.as_of}</span>
        </div>
      </div>

      <div className="mx-auto flex max-w-[1440px] flex-col gap-4 p-4">
        <div className="flex flex-col gap-4 xl:flex-row">
          {/* main chart */}
          <div className="flex-1 rounded-xl border border-border bg-card p-4">
            <div className="mb-2 flex items-baseline justify-between">
              <div className="flex items-baseline gap-2.5">
                <span className="text-sm font-bold">Where the count says we are</span>
                <span className="text-xs text-muted-foreground">
                  the two years around the top · linear scale
                </span>
              </div>
              <span className="text-xs text-[#c084fc]">◦ labels are Supercycle degree</span>
            </div>
            <RecentChart feed={feed} />
          </div>

          {/* readings rail */}
          <div className="flex w-full flex-none flex-col gap-3.5 xl:w-[400px]">
            {leading && (
              <div className="rounded-xl border border-border bg-card p-5">
                <div className="mb-3 flex items-center justify-between">
                  <span className="text-[11px] font-semibold uppercase tracking-wider text-muted-foreground">
                    Leading reading
                  </span>
                  <span className="rounded-full bg-primary px-2.5 py-0.5 text-[11px] font-semibold text-primary-foreground">
                    weight {Math.round(leading.weight * 100)}%
                  </span>
                </div>
                <div className="mb-3 text-[16px] font-bold">{readingTitle(leading)}</div>
                <div className="flex flex-col gap-2 text-[13px]">
                  <div className="flex justify-between">
                    <span className="text-muted-foreground">Structural zone</span>
                    <span className="font-mono font-semibold text-primary">
                      {fmtMoney(leading.zone[0])} – {fmtMoney(leading.zone[1])}
                    </span>
                  </div>
                  {leading.invalidation != null && (
                    <div className="flex justify-between">
                      <span className="text-muted-foreground">Count invalid above</span>
                      <span className="font-mono font-semibold text-sell">
                        {fmtMoney(leading.invalidation)}
                      </span>
                    </div>
                  )}
                </div>
              </div>
            )}
            {alt && (
              <div className="rounded-xl border border-border bg-card p-5">
                <div className="mb-2 flex items-center justify-between">
                  <span className="text-[11px] font-semibold uppercase tracking-wider text-muted-foreground">
                    Alternate reading
                  </span>
                  <span className="rounded-full border border-border px-2.5 py-0.5 text-[11px] font-semibold text-muted-foreground">
                    weight {Math.round(alt.weight * 100)}%
                  </span>
                </div>
                <div className="mb-1.5 text-[14px] font-bold">{readingTitle(alt)}</div>
                <p className="text-[13px] leading-relaxed text-muted-foreground">
                  Structural zone{" "}
                  <span className="font-mono text-[#e3b341]">
                    {fmtMoney(alt.zone[0])} – {fmtMoney(alt.zone[1])}
                  </span>
                </p>
              </div>
            )}
            <div className="rounded-xl border border-dashed border-border px-5 py-4">
              <p className="text-xs leading-relaxed text-muted-foreground">
                Forecast labels here are earned, not asserted. Every zone class is
                replayed against history the engine never saw, then held against
                matched random baselines — a bar no other Elliott Wave service
                runs. Zones render as structure; when a class clears the bar, it
                carries a forecast label with its measured rate. The ledger below
                keeps score in public.
              </p>
            </div>
          </div>
        </div>

        {/* full count */}
        <div className="rounded-xl border border-border bg-card p-4">
          <div className="mb-2 flex items-baseline gap-2.5">
            <span className="text-sm font-bold">The whole count</span>
            <span className="text-xs text-muted-foreground">
              {feed.pair} since inception, {feed.series_full[0][0]} · log scale
            </span>
          </div>
          <FullHistoryChart feed={feed} />
        </div>

        {/* ledger */}
        <div className="rounded-xl border border-border bg-card px-2 pb-2 pt-4">
          <div className="mb-3 flex items-baseline justify-between px-3">
            <div className="flex items-baseline gap-3">
              <span className="text-sm font-bold">The ledger — every call, resolved in public</span>
              <span className="text-xs text-muted-foreground">
                {t.resolved} walk-forward calls · {t.hit} hit · {t.miss} missed · {t.invalidated} invalidated
              </span>
            </div>
          </div>
          <div className="overflow-x-auto">
            <table className="w-full text-left text-[12.5px]">
              <thead>
                <tr className="border-b border-border text-[11px] font-semibold uppercase tracking-wider text-muted-foreground">
                  <th className="px-3.5 py-2.5">Called on</th>
                  <th className="px-3.5 py-2.5">Degree</th>
                  <th className="px-3.5 py-2.5">Reading</th>
                  <th className="px-3.5 py-2.5">Target zone</th>
                  <th className="px-3.5 py-2.5">Outcome</th>
                  <th className="px-3.5 py-2.5">Days</th>
                  <th className="px-3.5 py-2.5">Weight</th>
                </tr>
              </thead>
              <tbody>
                {feed.ledger.map((row, i) => {
                  const o = OUTCOME_STYLE[row.outcome];
                  return (
                    <tr key={i} className="border-b border-border/50">
                      <td className="px-3.5 py-2.5 font-mono text-muted-foreground">{row.date}</td>
                      <td className="px-3.5 py-2.5">{row.degree}</td>
                      <td className="px-3.5 py-2.5">{row.reading}</td>
                      <td className="px-3.5 py-2.5 font-mono">
                        {fmtMoney(row.zone[0])} – {fmtMoney(row.zone[1])}
                      </td>
                      <td className="px-3.5 py-2.5" style={{ color: o.dot }}>
                        <span className="mr-1.5 inline-block h-1.5 w-1.5 rounded-full"
                          style={{ background: o.dot }} />
                        {o.label}
                      </td>
                      <td className="px-3.5 py-2.5 font-mono text-muted-foreground">
                        {row.days != null ? `${row.days}d` : "—"}
                      </td>
                      <td className="px-3.5 py-2.5 font-mono text-muted-foreground">
                        {row.weight != null ? `${Math.round(row.weight * 100)}%` : "—"}
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        </div>

        <p className="pb-2 text-center text-[11px] text-muted-foreground">
          Structural analysis, not investment advice · engine {feed.engine}
        </p>
      </div>
    </div>
  );
}
